"""Zero-API verifier sensitivity replay for Experiment C."""

from __future__ import annotations

from collections import Counter, defaultdict
import math
from typing import Any, Mapping, Sequence

from .m2_episodic import EpisodeRecord
from .m3_semantic import VerifiedRule


SENSITIVITY_SCHEMA_VERSION = "finevo-rule-sensitivity-v1"
ALTERNATIVE_SUCCESS_WEIGHTS = (0.25, 0.50, 0.75)
OUTCOME_DEFINITIONS = (
    "utility_advantage_positive",
    "absolute_flow_utility",
    "three_period_cumulative_advantage_positive",
)


def _finite(value: Any, name: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise TypeError(f"{name} must be numeric")
    result = float(value)
    if not math.isfinite(result):
        raise ValueError(f"{name} must be finite")
    return result


def _integer(value: Any, name: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError(f"{name} must be an integer")
    return int(value)


def _criterion_success(
    episode: EpisodeRecord,
    *,
    definition: str,
    absolute_flow_threshold: float,
    rolling_advantage: Mapping[tuple[int, int], float],
) -> bool:
    if definition == "utility_advantage_positive":
        return episode.utility_advantage > 0
    if definition == "absolute_flow_utility":
        return episode.flow_utility > absolute_flow_threshold
    if definition == "three_period_cumulative_advantage_positive":
        return rolling_advantage[(episode.agent_id, episode.outcome_t)] > 0
    raise ValueError(f"unknown outcome definition {definition!r}")


def _rolling_three_period_advantage(
    episodes: Sequence[EpisodeRecord],
) -> dict[tuple[int, int], float]:
    by_agent: dict[int, dict[int, float]] = defaultdict(dict)
    for episode in episodes:
        by_agent[episode.agent_id][episode.outcome_t] = episode.utility_advantage
    result: dict[tuple[int, int], float] = {}
    for agent_id, values in by_agent.items():
        for outcome_t in sorted(values):
            result[(agent_id, outcome_t)] = sum(
                values.get(period, 0.0)
                for period in range(max(1, outcome_t - 2), outcome_t + 1)
            )
    return result


def _classify(
    rule: VerifiedRule,
    episode: EpisodeRecord,
    *,
    success: bool,
) -> str:
    if not rule.context_scope.matches(episode.pre_state):
        return "irrelevant"
    if not rule.condition.matches(episode.pre_state):
        return "irrelevant"
    compliant = rule.action_guidance.is_consistent(episode.executed_action)
    if compliant and success:
        return "support"
    if compliant:
        return "harmful_compliance"
    if success:
        return "alternative_success"
    return "alternative_failure"


def _verifier_values(config: Mapping[str, Any]) -> dict[str, Any]:
    required = {
        "min_candidate_support": int,
        "activation_min_support": int,
        "activation_min_margin": (int, float),
        "activation_confidence_threshold": (int, float),
        "retirement_patience": int,
        "retirement_confidence_threshold": (int, float),
    }
    result: dict[str, Any] = {}
    for name, expected in required.items():
        value = config.get(name)
        if isinstance(value, bool) or not isinstance(value, expected):
            raise TypeError(f"verifier_config.{name} has the wrong type")
        result[name] = value
    return result


def _replay_one(
    *,
    rule: VerifiedRule,
    episodes: Sequence[EpisodeRecord],
    definition: str,
    absolute_flow_threshold: float,
    alternative_success_weight: float,
    verifier: Mapping[str, Any],
    rolling_advantage: Mapping[tuple[int, int], float],
) -> dict[str, Any]:
    relevant = [
        episode
        for episode in episodes
        if episode.agent_id == rule.agent_id
    ] if hasattr(rule, "agent_id") else list(episodes)
    # ``agent_id`` is attached by the stream rather than the VerifiedRule
    # dataclass.  Callers pass same-agent episodes, so the fallback is deliberate.
    classifications = {
        episode.episode_id: _classify(
            rule,
            episode,
            success=_criterion_success(
                episode,
                definition=definition,
                absolute_flow_threshold=absolute_flow_threshold,
                rolling_advantage=rolling_advantage,
            ),
        )
        for episode in relevant
    }
    timestamps = sorted({episode.outcome_t for episode in relevant})
    activation_t: int | None = None
    retirement_t: int | None = None
    harmful_streak = 0
    active_exposure_steps = 0
    first_harmful_t: int | None = None
    timeline = []
    for current_t in timestamps:
        # Outcomes at ``current_t`` are generated by the action chosen before
        # that outcome is observed.  A candidate admitted from this outcome can
        # only affect the *next* decision, so activation-period observations
        # must not be counted as active exposure.  Conversely, a rule that was
        # already active at the start of the period did expose the actor even
        # when this outcome retires it.
        active_before_outcome = (
            activation_t is not None and retirement_t is None
        )
        observed = [
            episode
            for episode in relevant
            if episode.outcome_t <= current_t
            and classifications[episode.episode_id] != "irrelevant"
        ]
        counts = Counter(
            classifications[episode.episode_id] for episode in observed
        )
        support_score = float(counts["support"])
        contradiction_score = float(counts["harmful_compliance"]) + (
            alternative_success_weight * float(counts["alternative_success"])
        )
        margin = support_score - contradiction_score
        confidence = (support_score + 1.0) / (
            support_score + contradiction_score + 2.0
        )
        post_support = sum(
            classifications[episode.episode_id] == "support"
            and episode.outcome_t > rule.created_at
            for episode in observed
        )
        candidate_support = sum(
            episode.episode_id in set(rule.supporting_episode_ids)
            and classifications[episode.episode_id] == "support"
            for episode in observed
        )
        if (
            activation_t is None
            and current_t > rule.created_at
            and candidate_support >= int(verifier["min_candidate_support"])
            and counts["support"] >= int(verifier["activation_min_support"])
            and post_support >= 1
            and margin >= float(verifier["activation_min_margin"])
            and confidence
            >= float(verifier["activation_confidence_threshold"])
        ):
            activation_t = current_t

        current_rows = [
            episode for episode in observed if episode.outcome_t == current_t
        ]
        current_harmful = any(
            classifications[episode.episode_id] == "harmful_compliance"
            for episode in current_rows
        )
        if active_before_outcome:
            active_exposure_steps += 1
            if current_harmful:
                harmful_streak += 1
                if first_harmful_t is None:
                    first_harmful_t = current_t
            else:
                harmful_streak = 0
            # Match VerifiedSemanticRuleTrack.observe_outcome: either the
            # consecutive-failure patience limit OR a confidence-floor breach
            # retires the rule. Requiring both would understate harmful
            # exposure in this offline replay.
            if (
                harmful_streak >= int(verifier["retirement_patience"])
                or confidence
                < float(verifier["retirement_confidence_threshold"])
            ):
                retirement_t = current_t
        timeline.append(
            {
                "outcome_t": current_t,
                "counts": {
                    key: counts[key]
                    for key in (
                        "support",
                        "harmful_compliance",
                        "alternative_success",
                        "alternative_failure",
                    )
                },
                "margin": margin,
                "confidence": confidence,
                "active_before_outcome": active_before_outcome,
                "active": activation_t is not None and retirement_t is None,
            }
        )
    return {
        "rule_id": rule.rule_id,
        "activation_t": activation_t,
        "ever_active": activation_t is not None,
        "retirement_t": retirement_t,
        "active_exposure_steps": active_exposure_steps,
        "first_harmful_t": first_harmful_t,
        "harmful_to_retirement_delay": (
            retirement_t - first_harmful_t
            if retirement_t is not None and first_harmful_t is not None
            else None
        ),
        "timeline": timeline,
    }


def replay_rule_sensitivity(
    *,
    episode_rows: Sequence[Mapping[str, Any]],
    rule_rows: Sequence[Mapping[str, Any]],
    verifier_config: Mapping[str, Any],
    absolute_flow_threshold: float,
) -> dict[str, Any]:
    """Replay every frozen weight/outcome cell without making provider calls."""

    absolute_flow_threshold = _finite(
        absolute_flow_threshold, "absolute_flow_threshold"
    )
    verifier = _verifier_values(verifier_config)
    episodes = tuple(EpisodeRecord.from_dict(row) for row in episode_rows)
    rolling = _rolling_three_period_advantage(episodes)
    parsed_rules: list[tuple[int, VerifiedRule]] = []
    for row in rule_rows:
        if not isinstance(row, Mapping):
            raise TypeError("rule rows must be mappings")
        values = dict(row)
        agent_id = _integer(values.pop("agent_id"), "rule.agent_id")
        parsed_rules.append((agent_id, VerifiedRule.from_dict(values)))

    cells = []
    for weight in ALTERNATIVE_SUCCESS_WEIGHTS:
        for definition in OUTCOME_DEFINITIONS:
            rule_results = [
                _replay_one(
                    rule=rule,
                    episodes=[
                        episode
                        for episode in episodes
                        if episode.agent_id == agent_id
                    ],
                    definition=definition,
                    absolute_flow_threshold=absolute_flow_threshold,
                    alternative_success_weight=weight,
                    verifier=verifier,
                    rolling_advantage=rolling,
                )
                for agent_id, rule in parsed_rules
                if not rule.injected
            ]
            cells.append(
                {
                    "alternative_success_weight": weight,
                    "outcome_definition": definition,
                    "rule_count": len(rule_results),
                    "ever_active_count": sum(
                        row["ever_active"] for row in rule_results
                    ),
                    "retired_count": sum(
                        row["retirement_t"] is not None for row in rule_results
                    ),
                    "active_exposure_steps": sum(
                        row["active_exposure_steps"] for row in rule_results
                    ),
                    "rules": rule_results,
                }
            )
    return {
        "schema_version": SENSITIVITY_SCHEMA_VERSION,
        "absolute_flow_threshold": absolute_flow_threshold,
        "verifier_config": dict(verifier),
        "episode_count": len(episodes),
        "natural_rule_count": sum(not rule.injected for _, rule in parsed_rules),
        "cells": cells,
    }


__all__ = [
    "ALTERNATIVE_SUCCESS_WEIGHTS",
    "OUTCOME_DEFINITIONS",
    "SENSITIVITY_SCHEMA_VERSION",
    "replay_rule_sensitivity",
]
